CREATE DATABASE BANK;

USE BANK;

CREATE TABLE BANK(
ACCOUNT_ID INT,
ACCOUNT_TYPE varchar(200),
BALANCE FLOAT);

SELECT * FROM BANK;

CREATE TABLE TRANSACTIONS(
TRANSACTION_ID int,
TRANSACTION_DATE date,
AMOUNT decimal(10,2),
TRANSACTION_TYPE VARCHAR(20));

SELECT * FROM TRANSACTIONS;

CREATE TABLE BRANCHES(
BranchID int,
BRANCH_NAME VARCHAR(100),
BRANCH_ADD varchar(200),
BRANCH_PHONE varchar(15));

SELECT * FROM BRANCHES;

CREATE TABLE ACCOUNT_BRANCHES(
ASSIGNMENT_DATE DATE); 

SELECT * FROM ACCOUNT_BRANCHES;

CREATE TABLE LOANS(
LOAN_ID INT,
LOAN_AMOUNT float,
INTEREST_RATE float,
START_DATE DATE,
END_DATE DATE);

SELECT * FROM LOANS;

CREATE TABLE CUSTOMER(
CUSTOMER_ID int,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(100),
PHONE VARCHAR(15));

SELECT * FROM CUSTOMER;

ALTER TABLE CUSTOMER ADD DATE_OF_BIRTH date;

ALTER TABLE TRANSACTIONS MODIFY AMOUNT FLOAT;